### PR TITLE
Update getting_started

### PR DESCRIPTION
**Pull request by rrooij**
I updated the getting_started with a picture of the default key bindings and fixed something small.

On a side note:

Wouldn't it be nice to have a button in the home page with getting started? Just like "Installation"? Maybe the getting_started guide can have a link to the Installation page too.

### CODE REVIEW

**Comment by wm4** [comment]
>Wouldn't it be nice to have a button in the home page with getting started? Just like "Installation"? Maybe the getting_started guide can have a link to the Installation page too.

This was planned, but since we stopped working on this guide, it was never finished and not meant to be accessible in this state. I think.

**Comment by robin007bond** [comment]
I already thought so. Since it was commented in the installation page.

Anyway, I'm trying to bring it in the "reference" section in my fork. I think it is in a decent state now.

**Comment by robin007bond** [comment]
I think it's done now.

**Comment by pigoz** [comment]
I think we might want to use markdown for guides, since jekyll supports it out of the box IIRC and we could avoid the `Rakefile` task that way.

There are still .rst guides in the tree because I ad added a hack to make them work transparently in the past.

**Comment by robin007bond** [comment]
Thanks for merging it in the preview.

I also think that using Markdown for the guides is a good idea. You recalled correctly, jekyll supports markdown.

**Comment by wm4** [comment]
What happened to this?

**Comment by pigoz** [comment]
It's still here​
http://preview.mpv.io/guides/getting-started/#general-architecture

**Comment by wm4** [comment]
I mean, should we merge it?  Does @rrooij still want to change something?

**Comment by rrooij** [comment]
I'm not planning to change anything. But there are still a few issues:

* The abstract information is displayed in the beginner's guide: http://preview.mpv.io/guides/getting-started/ (should we remove that information? or is it possible to skip it when it gets converted to html?)
* We were talking about converting the guides to markdown, since that wouldn't require a separate method for converting the rst. 

I don't mind converting them to markdown, but it's a bit of a tedious work, so don't expect it to be ready anytime soon. 

What do you think about this?

**Comment by wm4** [comment]
So, whatever happened to this?

**Pull request closed without merging**
