### PR TITLE
OS X builds

### PR DESCRIPTION
**Pull request by stolendata**

### CODE REVIEW

**Comment by pigoz** [comment]
Great!

It looks like you built the binary using the 10.11. Maybe you should compile with the 10.10 SDK so it works on older OS X too (something like: `./configure --extra-cflags='-mmacosx-version-min=10.7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk'`)

I've noticed the download is a bit slow. If you don't want to get raped with a lot of traffic, I can create a stolendata.mpv.io CNAME on our CloudFlare so it keeps your server

**Comment by stolendata** [comment]
Unfortunately it's no longer possible to cross-compile against an older SDK, but I have rebuilt the executable with 10.9 as the lowest minimum target, without any warnings being issued, which should provide some guarantee for backwards compatibility. I have no 10.9/10.10 installation to test on, but I would be surprised if the build wouldn't run.

Thanks for the offer but no worries regarding my host being hammered - it's a VPS with unlimited traffic allowance and 200 mbit/s upstream, so it's able to take a beating even if the available shared bandwidth is a bit low now and then :)

**Comment by pigoz** [comment]
Nice!

@torque mentioned on IRC he wants to setup some automated nightly builds. In the meantime I'm merging this!

**Comment by Cpuroast** [comment]
@stolendata Your new 0.18.1 build doesn't run on OSX 10.10.5 but it runs fine on 10.11.5.

See error message on 10.10.5:

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
  Referenced from: /Applications/mpv.app/Contents/MacOS/lib/libavfilter.6.dylib
  Reason: image not found

**Comment by stolendata** [comment]
@Cpuroast Argh, seems I forgot to set the deployment target for all of the dependencies. My apologies. I'll try sort it out before the weekend.

**Comment by Cpuroast** [comment]
@stolendata You should put some basic information on the download page, something like this: http://sva.wakku.to/~chris/mpv_builds or this: https://mpv.srsfckn.biz/

**Comment by stolendata** [comment]
@Cpuroast Would you be so kind to test this build: https://laboratory.stolendata.net/~djinn/mpv-0.18.1.tar.gz

**Comment by Cpuroast** [comment]
That one works perfectly on 10.10.5.

**Pull request merged**
