### PR TITLE
Replace screenshot with an up-to-date one

### PR DESCRIPTION
**Pull request by sfan5**
method:
1. obtain backup copy of the movie
2. install opensuse KDE and recent mpv
3. switch theme to breeze dark
4. window decorations -> enable "circle around close button" & "titlebar background gradient", get rid of the 📌 button
6. `mpv --force-media-title="Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb" --geometry=996 --sid=no --start=00:23:52.473 --pause --vo=gpu-next file.mp4`
7. use spectacle to create window screenshot (make sure to move the mouse to show OSC)
8. crop bottom & right transparent pixels in gimp

### CODE REVIEW

**Comment by CounterPillow** [comment]
> make sure to move the mouse to show OSC

For future screenshotologists: Could've just hit Delete to make it always visible

**Comment by kasper93** [comment]
> window decorations

Do we really want to advertise specific window decorations? Maybe `--border=no` and use our own OSC title bar, which would look the same everywhere.

**Comment by sfan5** [comment]
I think mpv featuring KDE is very welcome variety among Windows and - worse - macOS screenshots you find on other generic "app" websites.

**Comment by kasper93** [comment]
Fair, I don't have a horse in this race. I personal don't use window decorations.

Just for the record it looks somethings like this:
image

**Comment by sfan5** [comment]
I could, but why? It's bigger for no reason.

**Comment by pigoz** [comment]
LGTM

**Pull request merged**
