### PR TITLE
images/mpv-screenshot: update with chapter marks

### PR DESCRIPTION
**Pull request by kasper93**
- KDE with Breeze Dark theme
- "Draw a circle around close button" enabled
- --start=00:23:52.473 --vo=gpu-next --video-crop=3584x2160 --target-trc=srgb --dither-depth=no --dscale=catmull_rom

### CODE REVIEW

**Review by sfan5 — COMMENTED** [review]
having the unofficial themed mpv icon there is not optimal

**Comment by kasper93** [comment]
> having the unofficial themed mpv icon there is not optimal

Updated with our icon.

**Comment by sfan5** [comment]
still different from either of these:
* https://github.com/mpv-player/mpv/blob/master/etc/mpv.svg
* https://github.com/mpv-player/mpv/blob/master/etc/mpv-gradient.svg

**Comment by kasper93** [comment]
> still different from either of these:

It is our official icon https://github.com/mpv-player/mpv/blob/master/etc/mpv-icon-8bit-16x16.png

**Comment by sfan5** [comment]
oh lol

**Review by sfan5 — APPROVED** [review]

**Comment by kasper93** [comment]
> oh lol

https://github.com/mpv-player/mpv/blob/master/etc/mpv-icon-8bit-32x32.png looks like this, if we prefer

image

**Pull request merged**
