### PR TITLE
Add tasty0tomato (my) build

### PR DESCRIPTION
**Pull request by tasty0tomato**
https://github.com/mpv-player/mpv/issues/8763

### And
1. I am not sure if my change will work, since I cannot build the website on my own computer. https://github.com/mpv-player/mpv.io/issues/91
2. I am not sure if gitee discussed in https://github.com/mpv-player/mpv/issues/8763 will be OK to everybody.

### CODE REVIEW

**Comment by avih** [comment]
I prefer to not add it for now.

As I noted at https://github.com/mpv-player/mpv/issues/8763 , I don't think it's ready to be included at the main page, for two main reasons:
1. As far as I can tell from your link, you don't specify which packages/versions and features are enabled, and you also don't describe exactly how you build it. In my opinion, a mandatory requirement to publish it at the home page is that users should be able to reproduce your build from scratch. This includes bootstrapping MXE (if that's what you use), any additional packages which you installed in MXE or built on your own (and if you built on your own - then instructions for those too), and finally the options when building mpv itself. Pretty much what @shinchiro does here https://github.com/shinchiro/mpv-winbuild-cmake
2. No offense, but we don't know you, and we don't know that your builds are not malicious. I'm assuming and hoping that it's fine, but we can't know that. In order to publish your builds at the main page you'll need to gather some community credit. There's no concrete way to do that, but for instance your github page is rather empty and you don't maintain popular projects - so we can't deduce much from that. As far as I know your builds are not downloaded by many users yet, and we don't have feedback about them. It's a kind of chicken-and-egg problem, but unfortunately we can't solve it for you.

So I suggest that you keep publishing your builds at https://github.com/mpv-player/mpv/issues/8763 . We can keep the issue open if you prefer, eventhough it's not really an issue. If you have some other places where you publish your builds, you can tell us where they are.

You can also join the mpv IRC channels and start helping users, so that over time we'll get to know you.

But really, before anything, you should make it possible for others to reproduce your build from scratch, with clear instructions and/or scripts.

For now though, I think it's not yet time to include your builds at the main page.

**Comment by tasty0tomato** [comment]
Understand.
I will try to make it better.

**Comment by avih** [comment]
Appreciated.

**Comment by tasty0tomato** [comment]
I have updated README.

**Comment by avih** [comment]
> I have updated README.

Nice. Much better.

Do note that the ffmpeg package in mxe is built without x265 encoding support, and without nvidia/cuda or vulkan support - https://github.com/mxe/mxe/blob/master/src/ffmpeg.mk . If you want to support these in your build, then you'll probably need to build ffmpeg yourself.

Also, I think your build does not support ANGLE GPU context. Not too critical I guess.

Also, your build does not have javascript support. While it's not mandatory in mpv, personally I think it's quite useful, because there are a lot more people who know js than people who know lua, so this makes mpv scripting a lot more accessible (and also there are js user scripts which can't be used in your build - https://github.com/mpv-player/mpv/wiki/User-Scripts ).

Overall, the description looks good, but I recommend you highlight the features which you support and those which you don't.

Note that shinchiro's builds do support the features mentioned here (and more), and people do use them.

**Comment by avih** [comment]
Also, does it support d3d11 output (at the configure output: `Direct3D 11 video output`)? IIRC this requires at least SPIR-V shaders compiler and shaders converter.

This is something I imagine users will really want.

**Comment by tasty0tomato** [comment]
I may know what I really want to do.
I spent sometimes to figure out how to made a better binary, so I checked out how [shinchiro](https://sourceforge.net/projects/mpv-player-windows/files) did and also https://github.com/shinchiro/mpv-winbuild-cmake . I thought [shinchiro](https://sourceforge.net/projects/mpv-player-windows/files) did much better than me so I decided to contribute to https://github.com/shinchiro/mpv-winbuild-cmake .

**Comment by avih** [comment]
> so I decided to contribute to https://github.com/shinchiro/mpv-winbuild-cmake .

What do you mean? send pull requests to his repository?

Regardless, if you do want to use his scripts, then you can fork his mpv-winbuild-cmake and use it yourself (never tried it myself) and maybe publish builds based on that? In recent weeks shinchiro didn't release builds, I guess he's busy with other things, so maybe you can publish builds from the same script yourself?

**Comment by tasty0tomato** [comment]
I tried to use https://github.com/shinchiro/mpv-winbuild-cmake to build mpv and it seems a little buggy. Waiting for [shinchiro](https://sourceforge.net/projects/mpv-player-windows/files)

**Comment by avih** [comment]
> it seems a little buggy. Waiting for shinchiro

As I said, it seems he responds slower than usual recently. I suggest you try to fix any issues yourself, publish a new build based on your fixes, and also send a pull-request to his repository to improve it.

But that's up to you of course.

Slightly off topic, you don't need to link to the user, we know who shinchiro is (and even if we didn't, there are already links to this repository earlier above).

If you want to notify someone, then you can mention them by adding @ just before the name/id, like so: @tasty0tomato (github will have auto-complete for convenience) so that will automatically send them an email that they were mentioned (at least by default).

**Pull request closed without merging**
